# TLS certificate and private key paths, if desired. These are totally
# optional! Another just-as-great solution for security is proxying this
# behind an Nginx instance.
cert_path = "/path/to/your/website.pem"
key_path = "/path/to/your/key.pem"

# Path to the SSH keypair to use.
private_key = "/path/to/.ssh/id_rsa"
public_key = "/path/to/.ssh/id_rsa.pub"

# DBSN.
db_path = "file:test.db?cache=shared&mode=memory"

# Password for the admin interface.
password = "myPassword"

# Set the address for your server.
address = ":8081"

# Set the address for your admin interface.
admin_address = ":8082"

# Path to the grading script to run on each upload.
grading_script = "./grade.sh"

# Define the maximum number of jobs that may run in parallel.
max_jobs = 5

# Refresh rate for the results page, in milliseconds.
results_refresh_rate = 3000

# Limit for request body size.
body_limit = "10K"

# Rate limit for clients, in requests per second.
rate_limit = 5
